--- src/etc/inc/globals.inc.orig
+++ src/etc/inc/globals.inc
@@ -100,7 +100,7 @@ $g = [
 	'services_dhcp_server_enable' => true,
 	'wireless_regex' => '/^(ath|athp|bwi|bwn|ipw|iwi|iwlwifi|iwm|iwn|malo|mwl|ral|rsu|rtwn|rum|run|uath|upgt|ural|urtw|urtwn|wi|wpi|wtap|zyd)[0-9]+/',
 	'help_base_url' => '/help.php',
-	'pkg_prefix' => 'pfSense-pkg-',
+	'pkg_prefix' => 'nonSense-pkg-',
 	'default_timezone' => 'Etc/UTC',
 	'language' => 'en_US',
 	'default_config_backup_count' => 30,
