--- src/etc/inc/globals.inc.orig
+++ src/etc/inc/globals.inc
@@ -78,9 +78,9 @@
 	'www_path' => '/usr/local/www',
 	'xml_rootobj' => 'pfsense',
 	'admin_group' => 'admins',
-	'product_name' => 'pfSense',
-	'product_label' => 'pfSense',
-	'product_label_html' => 'Netgate pfSense<sup>&#174;</sup>',
+	'product_name' => 'nonSense',
+	'product_label' => 'nonSense',
+	'product_label_html' => 'nonSense',
 	'product_version' => $product_version,
 	'product_copyright_years' => '2004 - ' . $present_year,
 	'disablehelpmenu' => false,
@@ -98,7 +98,7 @@
 	'services_dhcp_server_enable' => true,
 	'wireless_regex' => '/^(ath|athp|bwi|bwn|ipw|iwi|iwlwifi|iwm|iwn|malo|mwl|ral|rsu|rtwn|rum|run|uath|upgt|ural|urtw|urtwn|wi|wpi|wtap|zyd)[0-9]+/',
 	'help_base_url' => '/help.php',
-	'pkg_prefix' => 'pfSense-pkg-',
+	'pkg_prefix' => 'nonSense-pkg-',
 	'default_timezone' => 'Etc/UTC',
 	'language' => 'en_US',
 	'default_config_backup_count' => 30,
